lib/smart_ac_web/router.ex
defmodule SmartAcWeb.Router do
  use SmartAcWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SmartAcWeb.UserAuthPipeline
    plug SmartAcWeb.Plug.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug SmartAcWeb.AirConditionerAuthPipeline
  end

  pipeline :browser_authenticated do
    plug Guardian.Plug.EnsureAuthenticated, module: SmartAcWeb.Guardian,
      error_handler: SmartAcWeb.UserAuthErrorHandler
  end

  scope "/", SmartAcWeb do
    pipe_through :browser # Use the default browser stack

    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true
    scope "/admin" do
      get "/password_reset/new", AdminController, :new_password_reset
      post "/password_reset", AdminController, :password_reset

      get "/edit_password", AdminController, :edit_password
      put "/update_password", AdminController, :update_password
    end

    pipe_through :browser_authenticated

    get "/", AirConditionerController, :index
    resources "/admin", AdminController, only: [:index, :new, :create, :update]
    scope "/air_conditioner" do
      get "/search", AirConditionerController, :search
      post "/:id/resolve", AirConditionerController, :resolve
      resources "/", AirConditionerController, only: [:index, :show]
    end
  end

  # Other scopes may use custom stacks.
  scope "/api", SmartAcWeb do
    pipe_through :api

    post "/status_report/bulk", StatusReportController, :bulk
  end

  post "/api/air_conditioner", SmartAcWeb.AirConditionerController, :create
end

lib/smart_ac_web/views/layout_view.ex
defmodule SmartAcWeb.LayoutView do
  use SmartAcWeb, :view
end

lib/smart_ac_web/templates/layout/_header.html.eex
<nav class="flex justify-between bb b--white-10 bg-near-black">
  <%= link "SmartAC", to: "/", class: "link white-70 hover-white no-underline flex pa3" %>
  <div class="flex-grow pa3 flex items-center">
    <%= link "Devices", to: air_conditioner_path(@conn, :index), class: "f6 link dib white dim mr3 mr4-ns" %>
    <%= link "Admins", to: admin_path(@conn, :index), class: "f6 link dib white dim mr3" %>
    <%= if assigns[:current_user] do %>
      <%= link "Logout", to: session_path(@conn, :delete), method: "delete", class: "f6 link dib white dim mr3" %>
    <% else %>
      <%= link "Login", to: session_path(@conn, :new), class: "f6 link dib white dim mr3" %>
    <% end %>
  </div>
</nav>

lib/smart_ac_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SmartAC</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/tachyons.min.css") %>">
  </head>

  <body>
    <div class="avenir">
      <%= render SmartAcWeb.LayoutView, "_header.html", assigns %>

      <%= if get_flash(@conn, :info) do %>
        <p class="w-90 ba br-2 pa3 ma2 blue bg-washed-blue" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="w-90 ba br2 pa3 ma2 red bg-washed-red" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <main role="main" class="mw7 center">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>